language: generic

dist: trusty
sudo: required

services:
  - docker

env:
  global:
    - DOCKER_IMG="registry.gitlab.com/offa/docker-images"


matrix:
    include:
    - env: COMPILER=gcc-8
    - env: COMPILER=clang-6



before_install:
  - docker pull ${DOCKER_IMG}/${COMPILER}:stable

script:
   - docker run -v ${PWD}:/mnt -it ${DOCKER_IMG}/${COMPILER} /bin/bash -c "cd /mnt; script/ci_build.sh"
